spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SiSecurity
          jwk-set-uri: http://localhost:8080/realms/SiSecurity/protocol/openid-connect/certs

server:
  port: 5431

  jwt:
    auth:
      converter:
        principle-attribute: preferred-username
        resource-id: client_rest_api
